name: Run Notion Integration on PR Merge
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  notion-integrate:
    uses: alkira-admin/pm-automations/.github/workflows/notion.yml@arnav-2
    with:
      repo: ${{ github.repository }}
      pr_title: ${{ github.event.pull_request.title }}
